### ISSUE TITLE
Component attributes

### ISSUE THREAD

**Issue by Garito** [David-Desmaisons/ComponentFixture#1]
Hi!
Is it possible to prefix the component attributes to a fixed value?

example

```javascript
export default {
  name: 'app',
  components: {
    ComponentFixture,
    Editor,
    component
  },
  data: () => ({
    value: 'my value'
  })
}
```
and then
```html
<component-fixture class="content">
      
  <component v-model="value">
  </component>

  <Editor slot="control" slot-scope="scope" v-bind="scope"/>

</component-fixture>
```

Thanks!

**Comment by David-Desmaisons** [comment]
Hello @Garito this is a very good question. This is not possible right but this is a feature that I intend to deliver very soon. Stay tuned!!

**Comment by David-Desmaisons** [comment]
I added [defaults props](https://github.com/David-Desmaisons/ComponentFixture#props) to provide default props values

``` HTML
<component-fixture :defaults="{value: 45}">
```

**Comment by Garito** [comment]
Man, that has fast, thanks!
Upgrading already, will comment if necessary
Thanks again

**Comment by Garito** [comment]
Hi, again
I've installed it (yarn upgrade ComponentFixture) but I can't make it work
It doesn't raise any error but doesn't make any effect
Did I installed it correctly?
Should I paste here the actual code?

**Comment by David-Desmaisons** [comment]
Open another issue.
Describe the scenario and share the mark-up
